# Generated by Django 3.2.5 on 2021-07-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseDatos',
        ),
    ]
