# Generated by Django 3.2.5 on 2021-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210728_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatos',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=9),
        ),
    ]
